apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: react-native-image-picker
  description: A React Native module that allows you to use native UI to select media from the device library or directly from the camera
spec:
  type: library
  lifecycle: production
  domain: documents-platform
  system: document-upload
  owner: data-integration
